# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pt:
  languageCode: pt-br
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pt

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: cpcex_lab
  params:
    description: The Laboratory of Computational and Experimental Political Science develops scientific research projects and applied projects in Political Science and International Relations with intensive use of computational and experimental methods.
  menu:
    main:
      - name: About
        url: sobre/
        weight: 10
      - name: Projects
        url: '#projects'
        weight: 30
      - name: Talks
        url: '#talks'
        weight: 40
      - name: Team
        url: people/
        weight: 60
      - name: Contact
        url: '#contact'
        weight: 70

